workflows:
  android-debug:
    name: Vanz Music APK Build
    max_build_duration: 30
    instance_type: mac_mini_m2  # Ini mesin resmi yang 100% GRATIS 500 menit/bulan
    scripts:
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - support.vanzmusic@gmail.com
