workflows:
  android-debug:
    name: Vanz Music APK Build
    max_build_duration: 30
    instance_type: linux_x2 # Menggunakan mesin Linux gratisan khusus Android
    triggering:
      events:
        - push
      branches:
        - main
    scripts:
      - name: Build Android APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - support.vanzmusic@gmail.com
